In [1]:
import pandas as pd

In [8]:
import ast

In [2]:
df = pd.read_csv('new_per_imp_data/no_bootstrap_correlated_group_imps_df_linear_svc_pu.csv')

In [3]:
df

,Unnamed: 0,groups,means,stds
0,0,['ETHINYL ESTRADIOL_amount_mask'],-4.465774e-06,0.000010
1,1,['ACETAMINOPHEN WITH CODEINE_quantity_value_(0...,2.713382e-06,0.000010
2,2,"['ACETAMINOPHEN_amount_value_(-0.001, 1500.0]'...",1.631784e-04,0.000099
3,3,"['ACETAZOLAMIDE_quantity_value_(1.999, 14.0]',...",-7.348742e-07,0.000002
4,4,"['ACYCLOVIR_amount_value_(-0.001, 0.75]', 'ACY...",-4.869551e-06,0.000015
...,...,...,...,...
1212,1212,"['VERAPAMIL HCL_recency_value_(0.999, 264.0]',...",-9.093059e-06,0.000016
1213,1213,"['WARFARIN SODIUM_recency_value_(0.999, 246.0]...",-1.858989e-05,0.000013
1214,1214,"['ZALEPLON_recency_value_(-0.001, 127.0]', 'ZA...",-6.702699e-06,0.000004
1215,1215,"['ZOLMITRIPTAN_recency_value_(-0.001, 165.2]',...",9.852159e-07,0.000012
1216,1216,"['ZOLPIDEM TARTRATE_recency_value_(-0.001, 168...",1.184682e-05,0.000149

In [4]:
df_names = pd.read_csv('../train_test/feature_names.csv')

In [9]:
df['groups_list'] = df['groups'].apply(lambda l: ast.literal_eval(l))

In [10]:
df

,Unnamed: 0,groups,means,stds,groups_list
0,0,['ETHINYL ESTRADIOL_amount_mask'],-4.465774e-06,0.000010,[ETHINYL ESTRADIOL_amount_mask]
1,1,['ACETAMINOPHEN WITH CODEINE_quantity_value_(0...,2.713382e-06,0.000010,[ACETAMINOPHEN WITH CODEINE_quantity_value_(0....
2,2,"['ACETAMINOPHEN_amount_value_(-0.001, 1500.0]'...",1.631784e-04,0.000099,"[ACETAMINOPHEN_amount_value_(-0.001, 1500.0], ..."
3,3,"['ACETAZOLAMIDE_quantity_value_(1.999, 14.0]',...",-7.348742e-07,0.000002,"[ACETAZOLAMIDE_quantity_value_(1.999, 14.0], A..."
4,4,"['ACYCLOVIR_amount_value_(-0.001, 0.75]', 'ACY...",-4.869551e-06,0.000015,"[ACYCLOVIR_amount_value_(-0.001, 0.75], ACYCLO..."
...,...,...,...,...,...
1212,1212,"['VERAPAMIL HCL_recency_value_(0.999, 264.0]',...",-9.093059e-06,0.000016,"[VERAPAMIL HCL_recency_value_(0.999, 264.0], V..."
1213,1213,"['WARFARIN SODIUM_recency_value_(0.999, 246.0]...",-1.858989e-05,0.000013,"[WARFARIN SODIUM_recency_value_(0.999, 246.0],..."
1214,1214,"['ZALEPLON_recency_value_(-0.001, 127.0]', 'ZA...",-6.702699e-06,0.000004,"[ZALEPLON_recency_value_(-0.001, 127.0], ZALEP..."
1215,1215,"['ZOLMITRIPTAN_recency_value_(-0.001, 165.2]',...",9.852159e-07,0.000012,"[ZOLMITRIPTAN_recency_value_(-0.001, 165.2], Z..."
1216,1216,"['ZOLPIDEM TARTRATE_recency_value_(-0.001, 168...",1.184682e-05,0.000149,"[ZOLPIDEM TARTRATE_recency_value_(-0.001, 168...."

In [12]:
df_names['group'] = 0

In [13]:
df_names

                                           feature_name  group
0                         ETHINYL ESTRADIOL_amount_mask      0
1     ACETAMINOPHEN WITH CODEINE_quantity_value_(0.9...      0
2     ACETAMINOPHEN WITH CODEINE_quantity_value_(20....      0
3     ACETAMINOPHEN WITH CODEINE_quantity_value_(30....      0
4     ACETAMINOPHEN WITH CODEINE_quantity_value_(40....      0
...                                                 ...    ...
4984    ZOLPIDEM TARTRATE_recency_value_(-0.001, 168.0]      0
4985     ZOLPIDEM TARTRATE_recency_value_(168.0, 283.0]      0
4986     ZOLPIDEM TARTRATE_recency_value_(283.0, 332.0]      0
4987     ZOLPIDEM TARTRATE_recency_value_(332.0, 350.0]      0
4988     ZOLPIDEM TARTRATE_recency_value_(350.0, 364.0]      0

[4989 rows x 2 columns]

In [14]:
for i, l in enumerate(df['groups_list']):
    for v in l:
        df_names.loc[df_names['feature_name'] == v, 'group'] = i+1

In [15]:
df_names

                                           feature_name  group
0                         ETHINYL ESTRADIOL_amount_mask      1
1     ACETAMINOPHEN WITH CODEINE_quantity_value_(0.9...      2
2     ACETAMINOPHEN WITH CODEINE_quantity_value_(20....      2
3     ACETAMINOPHEN WITH CODEINE_quantity_value_(30....      2
4     ACETAMINOPHEN WITH CODEINE_quantity_value_(40....      2
...                                                 ...    ...
4984    ZOLPIDEM TARTRATE_recency_value_(-0.001, 168.0]   1217
4985     ZOLPIDEM TARTRATE_recency_value_(168.0, 283.0]   1217
4986     ZOLPIDEM TARTRATE_recency_value_(283.0, 332.0]   1217
4987     ZOLPIDEM TARTRATE_recency_value_(332.0, 350.0]   1217
4988     ZOLPIDEM TARTRATE_recency_value_(350.0, 364.0]   1217

[4989 rows x 2 columns]

In [16]:
df_names.to_csv('feature_groups.csv', index=False)